name: uztexsoft_scan
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  flutter_localization: ^0.2.2
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  mobile_scanner: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
